/** Extra SEO data per tool page: icon, target keywords and concrete use cases. */
export const SEO_EXTRA: Record<string, { icon: string; keywords: string[]; useCases: string[] }> = {
  'pdf-editor': { icon: 'FilePen', keywords: ['online pdf editor', 'edit pdf free', 'private pdf editor', 'pdf editor no upload', 'browser pdf editor'], useCases: ['Fix a typo in a contract before sending it', 'Fill in and sign a form without printing', 'Annotate a report for your team', 'Prepare a document for submission'] },
  'merge-pdf': { icon: 'Combine', keywords: ['merge pdf', 'combine pdf files', 'join pdf', 'merge pdf online free', 'merge pdf without upload'], useCases: ['Combine scanned pages into one file', 'Bundle invoices for accounting', 'Assemble an application package', 'Join chapters into a single book'] },
  'split-pdf': { icon: 'Split', keywords: ['split pdf', 'split pdf by pages', 'divide pdf', 'separate pdf pages', 'split pdf online free'], useCases: ['Send only the relevant chapter', 'Break a scanned batch into single documents', 'Separate odd and even scans', 'Create one file per page'] },
  'compress-pdf': { icon: 'Minimize2', keywords: ['compress pdf', 'reduce pdf size', 'shrink pdf', 'pdf compressor', 'compress pdf without upload'], useCases: ['Meet an email attachment limit', 'Speed up sharing scanned documents', 'Reduce storage for archives', 'Prepare files for a web upload form'] },
  'pdf-to-jpg': { icon: 'FileImage', keywords: ['pdf to jpg', 'convert pdf to jpg', 'pdf to image', 'pdf to jpeg', 'pdf to jpg online'], useCases: ['Share a page as a picture', 'Create thumbnails for a website', 'Post a document page on social media', 'Extract slides as images'] },
  'jpg-to-pdf': { icon: 'ImagePlus', keywords: ['jpg to pdf', 'convert image to pdf', 'photos to pdf', 'png to pdf', 'combine images into pdf'], useCases: ['Turn phone photos of receipts into one PDF', 'Create a portfolio from images', 'Scan-style documents from photos', 'Submit ID copies as a single file'] },
  'pdf-to-png': { icon: 'FileImage', keywords: ['pdf to png', 'convert pdf to png', 'pdf to png high quality', 'pdf page to image', 'lossless pdf image'], useCases: ['Get crisp images for presentations', 'Preserve transparency-free vector rendering', 'Create high-DPI previews', 'Archive pages as lossless images'] },
  'ocr-pdf': { icon: 'ScanText', keywords: ['ocr pdf', 'make pdf searchable', 'scanned pdf to text', 'pdf ocr online free', 'ocr without upload'], useCases: ['Search inside scanned contracts', 'Copy text from a photographed page', 'Digitise paper archives', 'Extract text from image-only PDFs'] },
  'sign-pdf': { icon: 'PenLine', keywords: ['sign pdf', 'e-sign pdf', 'add signature to pdf', 'sign pdf online free', 'draw signature pdf'], useCases: ['Sign an agreement from your phone', 'Add initials to every page', 'Countersign a form and return it', 'Date and name-stamp a document'] },
  'annotate-pdf': { icon: 'Highlighter', keywords: ['annotate pdf', 'highlight pdf', 'pdf comments', 'markup pdf', 'pdf annotation tool'], useCases: ['Review a draft with comments', 'Highlight key passages while studying', 'Mark up a design or drawing', 'Stamp documents as approved or rejected'] },
  'crop-pdf': { icon: 'Crop', keywords: ['crop pdf', 'trim pdf margins', 'crop pdf pages', 'remove white margins pdf', 'resize pdf pages'], useCases: ['Remove scanner borders', 'Trim margins for e-readers', 'Crop a single figure from a page', 'Make all pages the same size'] },
  'watermark-pdf': { icon: 'Droplets', keywords: ['watermark pdf', 'add watermark to pdf', 'pdf watermark online', 'confidential watermark', 'image watermark pdf'], useCases: ['Mark drafts as “DRAFT”', 'Add a logo to every page', 'Label confidential material', 'Discourage unauthorised copying'] },
  'rotate-pdf': { icon: 'RotateCw', keywords: ['rotate pdf', 'rotate pdf pages', 'flip pdf', 'fix sideways pdf', 'rotate pdf permanently'], useCases: ['Fix sideways scans', 'Rotate only landscape pages', 'Correct upside-down pages', 'Standardise orientation before printing'] },
  'extract-pdf-pages': { icon: 'FileOutput', keywords: ['extract pdf pages', 'extract pages from pdf', 'save selected pages pdf', 'pdf page extractor', 'pull pages from pdf'], useCases: ['Share a few pages of a long report', 'Save a single form from a packet', 'Extract every odd page for duplex fixes', 'Pull appendix pages out'] },
  'delete-pdf-pages': { icon: 'FileMinus', keywords: ['delete pdf pages', 'remove pages from pdf', 'delete pages pdf online', 'remove blank pages pdf', 'cut pages from pdf'], useCases: ['Remove blank scanned pages', 'Delete sensitive pages before sharing', 'Trim cover sheets', 'Drop duplicate pages'] },
  'reorder-pdf-pages': { icon: 'ArrowUpDown', keywords: ['reorder pdf pages', 'rearrange pdf pages', 'organize pdf', 'move pdf pages', 'sort pdf pages'], useCases: ['Fix pages scanned out of order', 'Move an appendix to the front', 'Reverse a back-to-front scan', 'Interleave two sources'] },
}
