export interface SeoPage {
  slug: string
  title: string
  h1: string
  description: string
  intro: string
  /** Real command opened in the editor (`?tool=`). */
  tool: string
  cta: string
  steps: string[]
  points: string[]
  faq: { q: string; a: string }[]
  related: string[]
}

const common = {
  privacy: { q: 'Are my files uploaded anywhere?', a: 'No. OurPDF runs entirely in your browser. Your files are read locally, processed by JavaScript and WebAssembly on your device, and never sent to a server.' },
  offline: { q: 'Does it work offline?', a: 'Yes. After your first visit the app is cached, so you can keep working without a connection.' },
}

export const SEO_PAGES: SeoPage[] = [
  {
    slug: 'pdf-editor',
    title: 'Free online PDF editor – private, in your browser',
    h1: 'PDF editor that never uploads your files',
    description: 'Edit, annotate, sign, organize and convert PDFs in your browser. No upload, no account. Add text, images, shapes, forms and more.',
    intro: 'OurPDF is a full-featured PDF editor that runs entirely on your device. Open a PDF, add text, highlights, drawings, images, form fields and signatures, reorder pages, then download the result.',
    tool: 'editor',
    cta: 'Open PDF editor',
    steps: ['Open or drop a PDF (or start from images or a blank page).', 'Use the toolbar: add text, annotate, draw, insert images, fill or build forms, sign.', 'Download the edited PDF. Your work is autosaved locally in the browser.'],
    points: ['Add text, images, shapes, stamps and signatures', 'Highlight, underline, strike out and add notes', 'Reorder, rotate, crop, merge and split pages', 'Fill and create form fields', 'Search text and run OCR on scans', 'Undo/redo for every action'],
    faq: [
      { q: 'Can I edit existing text in a PDF?', a: 'You can replace text by covering the original and typing new text over it (an overlay). Arbitrary PDF text can’t always be edited natively; to remove content for good use the Redact tool.' },
      common.privacy,
      common.offline,
    ],
    related: ['merge-pdf', 'annotate-pdf', 'sign-pdf', 'ocr-pdf'],
  },
  {
    slug: 'merge-pdf',
    title: 'Merge PDF files online – free, private, no upload',
    h1: 'Merge PDF files in your browser',
    description: 'Combine multiple PDFs into one document. Drag to reorder, no upload, no watermark. Files stay on your device.',
    intro: 'Combine several PDFs into a single file in seconds. Choose the files, put them in order and merge – everything happens locally.',
    tool: 'merge',
    cta: 'Merge PDFs',
    steps: ['Choose two or more PDFs (or drop them onto the editor).', 'Reorder them with the arrows.', 'Click Merge and download the combined PDF.'],
    points: ['Unlimited files, no watermark', 'Merge open documents including unsaved edits', 'Reorder pages afterwards in the organizer', 'Works offline'],
    faq: [{ q: 'Is there a file size limit?', a: 'Only your device’s memory. Large files are streamed for viewing; merging very large files needs enough RAM.' }, { q: 'What happens to form fields when merging?', a: 'Form fields from merged files are flattened into the page so their names cannot clash.' }, common.privacy],
    related: ['split-pdf', 'reorder-pdf-pages', 'compress-pdf', 'extract-pdf-pages'],
  },
  {
    slug: 'split-pdf',
    title: 'Split PDF into separate files – private, in-browser',
    h1: 'Split a PDF by range, every N pages, or page by page',
    description: 'Split PDFs by page ranges, every N pages, odd/even pages or selection. Download as a ZIP. Nothing is uploaded.',
    intro: 'Divide a large PDF into smaller documents. Define ranges like 1-3; 4-6, split every N pages, or separate each page.',
    tool: 'split',
    cta: 'Split a PDF',
    steps: ['Open your PDF.', 'Choose how to split: ranges, every N pages, single pages, odd or even.', 'Download the parts – bundled into one ZIP.'],
    points: ['Split by ranges or every N pages', 'Odd/even and selected pages', 'Includes your edits', 'Preview of resulting files'],
    faq: [{ q: 'Can I split by selected pages?', a: 'Yes – select pages in the thumbnails or organizer and choose “Selected pages”.' }, common.privacy],
    related: ['extract-pdf-pages', 'merge-pdf', 'delete-pdf-pages', 'reorder-pdf-pages'],
  },
  {
    slug: 'compress-pdf',
    title: 'Compress PDF online – reduce file size privately',
    h1: 'Compress PDFs without uploading them',
    description: 'Reduce PDF size with image recompression, downsampling and object cleanup. See the real result before downloading. 100% local.',
    intro: 'Shrink heavy PDFs by recompressing images, capping resolution and removing unused objects. The dialog shows the actual output size and savings.',
    tool: 'compress',
    cta: 'Compress a PDF',
    steps: ['Open the PDF.', 'Pick a preset (Lossless, Balanced, Smallest) or set JPEG quality and DPI.', 'Compare before/after and download.'],
    points: ['Presets and custom quality/resolution', 'Measures the real output size', 'Optionally remove metadata', 'Rasterize mode for maximum reduction'],
    faq: [{ q: 'Will compression reduce quality?', a: 'Lossless only repacks data. Balanced and Smallest recompress images as JPEG at lower quality/resolution.' }, common.privacy],
    related: ['pdf-to-jpg', 'merge-pdf', 'split-pdf', 'watermark-pdf'],
  },
  {
    slug: 'pdf-to-jpg',
    title: 'PDF to JPG converter – private, no upload',
    h1: 'Convert PDF pages to JPG images',
    description: 'Export PDF pages as JPG at up to 300 dpi. Convert selected pages, download as ZIP. Runs in your browser.',
    intro: 'Turn every page (or a selection) into JPG images, at the resolution you choose. Annotations and form values can be included.',
    tool: 'pdf-to-jpg',
    cta: 'Convert PDF to JPG',
    steps: ['Open the PDF.', 'Choose JPG, resolution (dpi) and quality.', 'Download images (ZIP for several pages).'],
    points: ['72–300 dpi', 'Adjustable JPG quality', 'Include annotations', 'Choose pages'],
    faq: [{ q: 'Can I get PNG instead?', a: 'Yes – see the PDF to PNG page.' }, common.privacy],
    related: ['pdf-to-png', 'jpg-to-pdf', 'compress-pdf', 'ocr-pdf'],
  },
  {
    slug: 'jpg-to-pdf',
    title: 'JPG to PDF converter – combine images into a PDF',
    h1: 'Convert JPG and other images to PDF',
    description: 'Turn JPG, PNG and WEBP images into a single PDF. Choose page size and order. Private, in-browser conversion.',
    intro: 'Create a PDF from one or many images. Pick fit-to-image or standard page sizes, reorder and convert.',
    tool: 'jpg-to-pdf',
    cta: 'Convert images to PDF',
    steps: ['Add images.', 'Order them and choose page size/orientation.', 'Create the PDF and download it.'],
    points: ['JPG, PNG, WEBP (TIFF where supported)', 'Fit to image, A4, Letter, A3, Legal', 'Correct EXIF orientation', 'Multiple images → one PDF'],
    faq: [{ q: 'Does it recompress my images?', a: 'Baseline JPEGs are embedded as-is without quality loss.' }, common.privacy],
    related: ['pdf-to-jpg', 'merge-pdf', 'compress-pdf', 'pdf-editor'],
  },
  {
    slug: 'pdf-to-png',
    title: 'PDF to PNG converter – lossless page images',
    h1: 'Convert PDF pages to PNG',
    description: 'Export PDF pages as high-resolution PNG images. Free, private, no uploads – runs in your browser.',
    intro: 'Render each page as a lossless PNG at the DPI you need, with or without your annotations.',
    tool: 'pdf-to-png',
    cta: 'Convert PDF to PNG',
    steps: ['Open the PDF.', 'Choose PNG and a resolution.', 'Download the images (ZIP for many).'],
    points: ['Lossless output', 'Up to 300 dpi', 'Pick pages', 'Includes edits if you want'],
    faq: [common.privacy, { q: 'Is there a page limit?', a: 'No, but very high dpi on large pages uses a lot of memory.' }],
    related: ['pdf-to-jpg', 'jpg-to-pdf', 'ocr-pdf', 'crop-pdf'],
  },
  {
    slug: 'ocr-pdf',
    title: 'OCR PDF online – make scanned PDFs searchable',
    h1: 'OCR scanned PDFs locally',
    description: 'Recognize text in scanned PDFs with Tesseract running in your browser. Search, copy and export text, or create a searchable PDF.',
    intro: 'Run optical character recognition without sending documents anywhere. Choose languages, recognise selected pages, then search, copy or export.',
    tool: 'ocr',
    cta: 'OCR a PDF',
    steps: ['Open a scanned PDF.', 'Choose languages and pages.', 'Recognise, then search, copy text or download a searchable PDF.'],
    points: ['English, Spanish, French, German, Italian, Portuguese', 'Language detection', 'Progress and cancel', 'Searchable PDF output'],
    faq: [{ q: 'Is OCR done on a server?', a: 'No – the OCR engine and language data are served with the app and run in a web worker on your device.' }, common.offline],
    related: ['pdf-editor', 'pdf-to-jpg', 'annotate-pdf', 'crop-pdf'],
  },
  {
    slug: 'sign-pdf',
    title: 'Sign PDF online – draw, type or upload your signature',
    h1: 'Sign PDFs privately',
    description: 'Add a drawn, typed or uploaded signature and initials to any PDF. Saved locally in your browser. Not uploaded.',
    intro: 'Create a signature by drawing, typing or uploading, then place, resize and rotate it. Save signatures for reuse – locally only.',
    tool: 'sign',
    cta: 'Sign a PDF',
    steps: ['Open the PDF.', 'Draw, type or upload your signature.', 'Click to place it, adjust, then download.'],
    points: ['Draw, type or upload', 'Initials, date and name', 'Saved signatures stay in your browser', 'Multiple signatures'],
    faq: [{ q: 'Is this a legally qualified digital signature?', a: 'No. This adds a visual e-signature image. Certificate-based digital signatures are not created.' }, common.privacy],
    related: ['pdf-editor', 'annotate-pdf', 'watermark-pdf', 'compress-pdf'],
  },
  {
    slug: 'annotate-pdf',
    title: 'Annotate PDF online – highlight, draw, comment',
    h1: 'Annotate PDFs in your browser',
    description: 'Highlight, underline, add notes, draw shapes and stamps on PDFs. Free, private and works offline.',
    intro: 'Mark up documents with highlights, underlines, strike-outs, sticky notes, freehand drawing, shapes, callouts and stamps.',
    tool: 'annotate',
    cta: 'Annotate a PDF',
    steps: ['Open the PDF.', 'Pick a markup tool and select text or draw.', 'Adjust colour and thickness, then download.'],
    points: ['Highlight, underline, strike, squiggly', 'Sticky notes and callouts', 'Pen, marker, shapes, arrows, clouds', 'Stamps: approved, draft, confidential…'],
    faq: [common.privacy, { q: 'Can I edit annotations later?', a: 'Yes, until you flatten. Your project is autosaved locally with editable annotations.' }],
    related: ['pdf-editor', 'sign-pdf', 'ocr-pdf', 'watermark-pdf'],
  },
  {
    slug: 'crop-pdf',
    title: 'Crop PDF pages online – visual crop tool',
    h1: 'Crop PDF pages',
    description: 'Crop PDF pages visually or by exact margins. Apply to one, selected or all pages. Auto-trim white margins. Private.',
    intro: 'Draw a crop rectangle, enter exact margins, centre-crop to custom dimensions or trim white space automatically.',
    tool: 'crop',
    cta: 'Crop a PDF',
    steps: ['Open the PDF.', 'Draw the crop area or enter margins.', 'Apply to current, selected or all pages.'],
    points: ['Visual crop tool', 'Exact margins and dimensions', 'Auto-trim white margins', 'Reset crop any time'],
    faq: [{ q: 'Does cropping delete the hidden content?', a: 'Like most editors it sets the visible page box; cropped content remains in the file. Use Redact to remove content permanently.' }, common.privacy],
    related: ['rotate-pdf', 'pdf-to-png', 'reorder-pdf-pages', 'pdf-editor'],
  },
  {
    slug: 'watermark-pdf',
    title: 'Add watermark to PDF – text or image, tiled',
    h1: 'Watermark PDFs',
    description: 'Add text or image watermarks to PDF pages: position, rotate, opacity and tile. Private and offline-capable.',
    intro: 'Stamp “Confidential”, a logo or any text across your pages. Control size, colour, rotation, opacity and tiling, and apply to all or selected pages.',
    tool: 'watermark',
    cta: 'Add a watermark',
    steps: ['Open the PDF.', 'Enter text or choose an image.', 'Set position, rotation, opacity and pages, then add.'],
    points: ['Text or image', 'Tile across the page', 'Rotate and set opacity', 'Selected pages'],
    faq: [common.privacy, { q: 'Can I remove a watermark later?', a: 'Yes – watermarks stay editable in the editor until you flatten and save, and can be removed from the dialog.' }],
    related: ['sign-pdf', 'annotate-pdf', 'compress-pdf', 'pdf-editor'],
  },
  {
    slug: 'rotate-pdf',
    title: 'Rotate PDF pages online – permanently',
    h1: 'Rotate PDF pages',
    description: 'Rotate single, selected or all PDF pages by 90°, 180° or 270° and save permanently. Private and free.',
    intro: 'Fix sideways scans in seconds: rotate one page, a selection or the whole document, then download.',
    tool: 'rotate',
    cta: 'Rotate PDF pages',
    steps: ['Open the PDF and open the organizer.', 'Select pages and rotate.', 'Download the corrected PDF.'],
    points: ['Bulk rotate', 'Reset rotation', 'Undo/redo', 'Works with mixed page sizes'],
    faq: [common.privacy, { q: 'Is rotation saved in the file?', a: 'Yes, the page rotation is written into the exported PDF.' }],
    related: ['reorder-pdf-pages', 'crop-pdf', 'delete-pdf-pages', 'merge-pdf'],
  },
  {
    slug: 'extract-pdf-pages',
    title: 'Extract pages from PDF – save selected pages',
    h1: 'Extract pages from a PDF',
    description: 'Extract selected, odd, even or ranged pages into a new PDF. Private, in-browser.',
    intro: 'Pull the pages you need into a new file – by range, selection, odd or even.',
    tool: 'extract',
    cta: 'Extract pages',
    steps: ['Open the PDF.', 'Choose pages (range, selection, odd/even).', 'Download the new PDF.'],
    points: ['Ranges like 1-3, 7, 10-', 'Odd or even pages', 'Selected thumbnails', 'Original stays untouched'],
    faq: [common.privacy, { q: 'Does it include my edits?', a: 'Yes – extracted pages include annotations and text you added.' }],
    related: ['split-pdf', 'delete-pdf-pages', 'merge-pdf', 'reorder-pdf-pages'],
  },
  {
    slug: 'delete-pdf-pages',
    title: 'Delete pages from PDF online',
    h1: 'Delete PDF pages',
    description: 'Remove unwanted pages from a PDF. Deleted content is fully removed from the saved file. Private and free.',
    intro: 'Select pages in the organizer and delete them. When you save, the removed pages’ data is purged from the file rather than merely hidden.',
    tool: 'delete',
    cta: 'Delete PDF pages',
    steps: ['Open the PDF and the organizer.', 'Select the pages to remove and delete.', 'Download the cleaned PDF.'],
    points: ['Bulk delete', 'Undo/redo', 'Data of deleted pages is purged on save', 'Ranges and odd/even selection'],
    faq: [{ q: 'Is the deleted page really gone?', a: 'Yes. On export, unreferenced objects are removed so the deleted page’s content is not left in the file.' }, common.privacy],
    related: ['extract-pdf-pages', 'split-pdf', 'reorder-pdf-pages', 'merge-pdf'],
  },
  {
    slug: 'reorder-pdf-pages',
    title: 'Reorder PDF pages – drag and drop',
    h1: 'Reorder PDF pages',
    description: 'Rearrange PDF pages with drag and drop. Move, duplicate, rotate and delete pages in a visual organizer. Private.',
    intro: 'Open the organizer, drag pages into the right order and download. Multi-select to move several pages at once.',
    tool: 'reorder',
    cta: 'Reorder pages',
    steps: ['Open the PDF and the organizer.', 'Drag thumbnails to reorder.', 'Download the rearranged PDF.'],
    points: ['Drag & drop (touch friendly)', 'Move several pages at once', 'Reverse and sort', 'Undo/redo'],
    faq: [common.privacy, common.offline],
    related: ['rotate-pdf', 'delete-pdf-pages', 'merge-pdf', 'extract-pdf-pages'],
  },
]

export const SEO_MAP = new Map(SEO_PAGES.map((p) => [p.slug, p]))

/** Maps `?tool=` values to the editor command they launch. `immediate` tools do not need an open document. */
export const TOOL_LAUNCH: Record<string, { command: string; immediate?: boolean; hint: string }> = {
  merge: { command: 'file.merge', immediate: true, hint: 'Add the PDFs you want to merge.' },
  'jpg-to-pdf': { command: 'file.importImages', immediate: true, hint: 'Choose the images to convert.' },
  split: { command: 'pages.split', hint: 'Open the PDF you want to split.' },
  compress: { command: 'opt.compress', hint: 'Open the PDF you want to compress.' },
  'pdf-to-jpg': { command: 'convert.toJpg', hint: 'Open the PDF you want to convert.' },
  'pdf-to-png': { command: 'convert.toPng', hint: 'Open the PDF you want to convert.' },
  ocr: { command: 'ocr.run', hint: 'Open the scanned PDF.' },
  sign: { command: 'sign.create', hint: 'Open the PDF you want to sign.' },
  annotate: { command: 'tool.highlight', hint: 'Open the PDF you want to annotate.' },
  crop: { command: 'pages.crop', hint: 'Open the PDF you want to crop.' },
  watermark: { command: 'wm.add', hint: 'Open the PDF you want to watermark.' },
  rotate: { command: 'pages.organizer', hint: 'Open the PDF – select pages in the organizer and rotate them.' },
  extract: { command: 'pages.extract', hint: 'Open the PDF you want to extract pages from.' },
  delete: { command: 'pages.organizer', hint: 'Open the PDF – select pages in the organizer and delete them.' },
  reorder: { command: 'pages.organizer', hint: 'Open the PDF – drag pages to reorder them.' },
}
