/**
 * Plain-language summary of what every command does. Shown in tooltips, the command palette, the mobile menu and the
 * "Tool guide". Keep each entry to one or two short sentences and be honest about limits.
 */
export const COMMAND_HELP: Record<string, string> = {
  // File
  'file.open': 'Open one or more PDFs (or images, DOCX, XLSX, HTML, text) from your device. Files never leave your browser.',
  'file.openClipboard': 'Import a PDF or an image that you copied to the clipboard.',
  'file.new': 'Create a blank PDF of any size, or build one from text.',
  'file.importImages': 'Turn JPG / PNG / WebP images into a PDF, one image per page, with page size and margins you choose.',
  'file.save': 'Download the edited PDF with all your changes applied.',
  'file.saveAs': 'Download the edited PDF under a new file name.',
  'file.saveAll': 'Download every open document, one file each.',
  'file.export': 'Export the document, selected pages, images (PNG/JPG), text, HTML or annotations.',
  'file.print': 'Preview pages and print them from your browser, with your edits included.',
  'file.merge': 'Combine several PDFs into one. Reorder the files and choose which pages to include.',
  'file.projects': 'Reopen, rename, duplicate or delete documents autosaved in this browser, including earlier versions.',
  'file.exportProject': 'Save the document and all its editable objects as a .ourpdf project file you can reopen later or on another device.',
  'file.importProject': 'Open a .ourpdf project file exported earlier, with every edit still editable.',
  'file.metadata': 'View and edit the title, author, subject and keywords, or strip all metadata on export.',
  'file.close': 'Close the current document tab (you are asked first if it has unsaved changes).',
  'file.closeOthers': 'Close every tab except the current one.',
  'file.closeAll': 'Close every open document tab.',
  // Edit
  'edit.undo': 'Undo the last change. History is kept per document.',
  'edit.redo': 'Redo the change you just undid.',
  'edit.redo2': 'Alternate shortcut for Redo.',
  'edit.cut': 'Cut the selected objects to the clipboard.',
  'edit.copy': 'Copy the selected objects (or selected page text).',
  'edit.paste': 'Paste copied objects or an image from the clipboard onto the page.',
  'edit.delete': 'Delete the selected objects.',
  'edit.duplicate': 'Make a copy of the selected objects, slightly offset.',
  'edit.selectAll': 'Select every object on the current page.',
  'edit.find': 'Search the text of the whole document, with case, whole-word and regular-expression options.',
  'edit.replace': 'Find text and replace it with overlay text (the original stays underneath until you redact it).',
  'edit.front': 'Move the selection above everything else on the page.',
  'edit.forward': 'Move the selection one step up in the stacking order.',
  'edit.backward': 'Move the selection one step down in the stacking order.',
  'edit.back': 'Move the selection below all other objects.',
  'edit.lock': 'Lock the selected objects so they cannot be moved, resized or edited by accident.',
  'edit.unlock': 'Unlock the selected objects.',
  'edit.clearHistory': 'Forget the undo / redo history of this document (your edits stay).',
  'edit.cancel': 'Leave the current tool and deselect everything.',
  // Tools
  'tool.select': 'Select, move, resize, rotate and edit objects. Double-click text to edit it.',
  'tool.hand': 'Drag the page to pan around. Hold Space for a temporary hand in any tool.',
  'tool.highlight': 'Highlight selected text (or an area of a scanned page) in a colour.',
  'tool.underline': 'Underline the text you select on the page.',
  'tool.strike': 'Strike through selected text.',
  'tool.squiggly': 'Draw a wavy underline under selected text, handy for flagging wording.',
  'tool.note': 'Drop a sticky note with a comment. Notes are written to the PDF as real annotations.',
  'tool.pen': 'Draw freehand with a smooth pen line.',
  'tool.pencil': 'Sketch with a thin, textured pencil stroke.',
  'tool.marker': 'Draw thick, semi-transparent marker strokes.',
  'tool.brush': 'Paint pressure-style brush strokes.',
  'tool.eraser': 'Erase whole freehand strokes by touching them.',
  'tool.line': 'Draw a straight line. Hold Shift for 15° angles.',
  'tool.arrow': 'Draw a line with an arrowhead.',
  'tool.darrow': 'Draw a line with arrowheads at both ends.',
  'tool.rect': 'Draw a rectangle with stroke, fill and dash options. Hold Shift for a square.',
  'tool.rrect': 'Draw a rectangle with rounded corners.',
  'tool.ellipse': 'Draw an ellipse. Hold Shift for a circle.',
  'tool.polygon': 'Draw a regular polygon; set the number of sides in the properties.',
  'tool.star': 'Draw a star shape; choose the number of points, colours and outline in the properties.',
  'tool.cloud': 'Draw a revision cloud to circle areas that need attention.',
  'tool.path': 'Draw a Bézier path: click to add points, drag for curves, double-click to finish.',
  'tool.callout': 'Add a text box with a pointer tail that points at something on the page.',
  'tool.stamp': 'Place a stamp such as APPROVED, DRAFT or CONFIDENTIAL; stamps can show the date.',
  'annotate.markupArea': 'Switch highlight / underline tools between selecting text and dragging an area (for scanned pages).',
  'annotate.customStamp': 'Use your own image (logo, seal) as a stamp.',
  'annotate.dateStamp': 'Stamp today’s date on the page.',
  'annotate.stampDialog': 'Pick a stamp, colour and whether it shows the date.',
  'annotate.link': 'Draw a clickable area that opens a web address, an email or another page. Saved as a native PDF link.',
  'annotate.editLink': 'Change the target of the selected link.',
  'annotate.removeLink': 'Remove the selected link (or the link on selected text).',
  // Text
  'text.add': 'Click or drag on the page and type to add new text with any font, size and colour.',
  'text.edit': 'Click existing text to change it. The line is selected, the font is detected and reused where possible, and the original is covered. Use Redact to remove the original for good.',
  'text.heading': 'Add a heading (larger, bold text) to the page.',
  'text.list': 'Add a bulleted or numbered list.',
  'text.bold': 'Make the selected text bold (standard and library fonts).',
  'text.italic': 'Make the selected text italic (standard and library fonts).',
  'text.underline': 'Underline the selected text object.',
  'text.strike': 'Strike through the selected text object.',
  'text.font': 'Load your own TTF, OTF or WOFF font to use in text you add. It is embedded on export.',
  // Images
  'image.insert': 'Add an image (PNG, JPG, WebP…) to the page. Then resize, crop, flip and adjust brightness or contrast.',
  'image.replace': 'Swap the selected image for another one, keeping its position and size.',
  'image.rotateCw': 'Rotate the selection 90° clockwise.',
  'image.rotateCcw': 'Rotate the selection 90° counter-clockwise.',
  'image.flipH': 'Mirror the image left to right.',
  'image.flipV': 'Mirror the image top to bottom.',
  // Pages
  'pages.addBlank': 'Insert an empty page after the current one.',
  'pages.delete': 'Remove the selected pages. The removed content is not kept in the saved file.',
  'pages.duplicate': 'Duplicate the selected pages.',
  'pages.rotateCw': 'Rotate the selected pages 90° clockwise.',
  'pages.rotateCcw': 'Rotate the selected pages 90° counter-clockwise.',
  'pages.rotate180': 'Turn the selected pages upside down.',
  'pages.resetRotation': 'Undo any rotation applied to the selected pages.',
  'pages.moveUp': 'Move the selected pages earlier in the document.',
  'pages.moveDown': 'Move the selected pages later in the document.',
  'pages.extract': 'Save chosen pages (a range, odd/even, or a selection) as a new PDF.',
  'pages.split': 'Split the PDF into several files by page count, ranges or single pages, downloaded as a ZIP.',
  'pages.insertPdf': 'Insert pages from another PDF at a position you choose.',
  'pages.replace': 'Replace the current page with a page from another PDF.',
  'pages.copy': 'Copy the selected pages so they can be pasted elsewhere.',
  'pages.paste': 'Paste the copied pages after the current page.',
  'pages.reverse': 'Reverse the order of all pages.',
  'pages.sort': 'Sort the pages by their size (small to large).',
  'pages.sortOriginal': 'Return the pages to their original order.',
  'pages.labels': 'Set page labels such as i, ii, iii then 1, 2, 3; viewers show them in the page box.',
  'pages.crop': 'Crop the selected pages by margins, or trim white space automatically.',
  'pages.cropTool': 'Drag a crop rectangle on the page and apply it. Content outside stays in the file, only hidden.',
  'pages.setup': 'Change page size, add margins, centre or align the content, and make mixed page sizes uniform.',
  'pages.organizer': 'See all pages as a grid to drag, rotate, delete, duplicate and reorder them.',
  'pages.bookmark': 'Add a bookmark (outline entry) for the current page.',
  // Forms
  'form.field-text': 'Add a fillable text field (single line or multi-line, with optional validation).',
  'form.field-checkbox': 'Add a checkbox that can be ticked and unticked when the form is filled.',
  'form.field-radio': 'Add a radio button; buttons with the same name form a group.',
  'form.field-dropdown': 'Add a dropdown list of choices.',
  'form.field-listbox': 'Add a list box where several options are visible.',
  'form.field-button': 'Add a push button with your own label.',
  'form.field-date': 'Add a field for entering a date.',
  'form.field-signature': 'Add a signature field placeholder where someone can place their signature image.',
  'form.fill': 'Fill in form fields by clicking them.',
  'form.edit': 'Move, resize and configure form fields (name, required, validation, options).',
  'form.validate': 'Check required fields and formats and list what is missing.',
  'form.reset': 'Clear all fields back to their default values.',
  'form.data': 'Export the field values to JSON or CSV, or import values from a file.',
  'form.flatten': 'Turn form fields into ordinary page content so they can no longer be edited.',
  // Sign
  'sign.create': 'Create a signature by drawing, typing or uploading an image, then place it on the page. This is a visual signature, not a certificate-based digital signature.',
  'sign.date': 'Insert today’s date as text.',
  'sign.name': 'Insert your name as text where you click.',
  // Security
  'sec.security': 'Protect the PDF with an AES-256 password. Permission flags (print, copy, edit) are advisory and only honoured by compliant viewers.',
  'sec.removeMeta': 'Strip all metadata (author, title, dates, producer) from the exported file.',
  'sec.redact': 'Draw a box over content to remove it permanently. The page is re-rendered so the covered content is really gone.',
  'sec.redactText': 'Search for words or patterns and mark every match for redaction.',
  'sec.applyRedactions': 'Permanently burn all marked redactions into the pages and remove the covered text.',
  'sec.redactPreview': 'Show or hide how the page will look once redactions are applied.',
  // OCR & convert
  'ocr.run': 'Recognise text in scanned pages or images (Tesseract, runs locally), then search, copy or export a searchable PDF.',
  'ocr.clear': 'Remove OCR results from the document.',
  'convert.dialog': 'Convert this PDF to images, text or HTML, or turn images, DOCX, XLSX, HTML or text into a PDF. PDF → Word/Excel is not offered because it cannot be done reliably in a browser.',
  'convert.toPng': 'Export every page as a lossless PNG image.',
  'convert.toJpg': 'Export every page as a JPG image with adjustable quality.',
  'convert.toText': 'Export the text of the document as a .txt file (uses OCR text if you ran OCR).',
  'convert.toHtml': 'Export the text of the document as simple HTML.',
  'convert.canvasToPdf': 'Render the current page (with your edits) as an image and save it as a new PDF.',
  'convert.exportAnnotations': 'Export your annotations as JSON.',
  // Optimize
  'opt.compress': 'Shrink the file by recompressing images and removing unused data. Before/after sizes are measured, not estimated.',
  'opt.flatten': 'Bake all annotations into the page content so they cannot be changed.',
  // Watermark / header / footer
  'wm.add': 'Stamp text or an image diagonally or tiled across pages, with opacity and rotation.',
  'hf.header': 'Add repeating header text with {page}, {total}, {date} and {label} placeholders.',
  'hf.footer': 'Add repeating footer text with {page}, {total}, {date} and {label} placeholders.',
  'hf.bates': 'Add sequential Bates numbers (prefix, number, suffix) to every page for legal documents.',
  'hf.pageNumbers': 'Add “Page X of Y” numbers to the pages.',
  // View
  'view.zoomIn': 'Zoom in on the document for a closer look.',
  'view.zoomOut': 'Zoom out to see more of the page.',
  'view.zoom100': 'Show the document at its actual size.',
  'view.fitWidth': 'Fit the page width to the window.',
  'view.fitPage': 'Fit the whole page in the window.',
  'view.fitHeight': 'Fit the page height to the window.',
  'view.continuous': 'Scroll through pages continuously.',
  'view.single': 'Show one page at a time instead of scrolling.',
  'view.two': 'Show two pages side by side.',
  'view.twoCover': 'Show two pages side by side with the first page alone, like a book.',
  'view.vertical': 'Scroll pages top to bottom.',
  'view.horizontal': 'Scroll pages left to right.',
  'view.rotateCw': 'Rotate how the document is displayed (does not change the file).',
  'view.rotateCcw': 'Rotate the display counter-clockwise (does not change the file).',
  'view.fullscreen': 'Use the whole screen for the editor.',
  'view.presentation': 'Show pages full screen, one at a time, for presenting.',
  'view.left': 'Show or hide the left sidebar (thumbnails, bookmarks, attachments, layers, search).',
  'view.right': 'Show or hide the Properties panel for the selected object.',
  'view.theme': 'Switch between light, dark and system theme.',
  'view.highContrast': 'Increase contrast for easier reading.',
  'view.reduceMotion': 'Turn off animations and transitions.',
  'view.lowMemory': 'Render with smaller caches and lower quality to save memory on big files or small devices.',
  'view.settings': 'Rendering quality, history length, author name and other preferences.',
  'view.thumbnails': 'Show page thumbnails in the sidebar.',
  'view.outline': 'Show and edit bookmarks (the document outline).',
  'view.attachments': 'Show and add files attached to the PDF.',
  'view.layers': 'Show layers to hide, lock or reorder groups of objects.',
  'view.pages': 'Show the pages panel in the sidebar.',
  'nav.first': 'Jump to the first page of the document.',
  'nav.prev': 'Go back one page.',
  'nav.next': 'Go forward one page.',
  'nav.last': 'Jump to the last page of the document.',
  // Help
  'help.shortcuts': 'See and customise every keyboard shortcut.',
  'help.tools': 'A searchable guide to every tool and what it does.',
  'help.about': 'How OurPDF keeps your files private, and what it can and cannot do.',
}

/** Field / control help shown when hovering a label in the toolbar options or Properties panel. */
export const FIELD_HELP: Record<string, string> = {
  X: 'Distance from the left edge of the page, in points (1 pt = 1/72 inch).',
  Y: 'Distance from the top edge of the page, in points.',
  Width: 'Width of the object in points.',
  Height: 'Height of the object in points.',
  Rotation: 'Rotate the object around its centre, in degrees.',
  Opacity: 'How see-through the object is: 100% is solid, lower values let the page show through.',
  Font: 'Typeface used for the text. Fonts found in the PDF and the bundled font library are listed too.',
  Size: 'Text size in points.',
  'Font size': 'Text size in points.',
  Style: 'Bold, italic, underline and strikethrough.',
  Colour: 'Colour of the text or stroke.',
  'Text colour': 'Colour of the text.',
  Highlight: 'Background colour behind the text.',
  Align: 'Align the text left, centre, right or justified inside its box.',
  'Line height': 'Space between lines as a multiple of the font size (1.2 is normal).',
  Spacing: 'Extra space between characters, in points.',
  'Character spacing': 'Extra space between characters, in points.',
  List: 'Turn the paragraphs into a bulleted or numbered list.',
  Wrap: 'When on, long lines wrap at the box edge. Off keeps each line on one line and grows the box.',
  'Auto-fit': 'Shrink the text automatically so it always fits its box.',
  Border: 'Draw a border around the text box.',
  Hyperlink: 'Make the text a link to a web address.',
  Stroke: 'Outline colour of the shape.',
  Fill: 'Fill colour of the shape.',
  'Stroke width': 'Thickness of the outline in points.',
  Width_: 'Thickness of the line in points.',
  Dash: 'Solid, dashed or dotted outline.',
  Brush: 'Brush type: pen, pencil, marker or brush.',
  Brightness: 'Make the image lighter or darker.',
  Contrast: 'Difference between light and dark areas of the image.',
  Saturation: 'Colour intensity of the image (0 is grey).',
  Grayscale: 'Convert the image to shades of grey.',
  Blur: 'Soften the image.',
  Sharpen: 'Increase edge sharpness of the image.',
  Quality: 'JPEG quality used when the image is saved into the PDF. 100% keeps it lossless.',
  Label: 'Text shown on the stamp or field.',
  Reason: 'Reason recorded for the redaction.',
  Name: 'Internal name of the form field (fields with the same name share a value).',
  Required: 'The field must be filled before the form validates.',
  'Read-only': 'The field can be seen but not changed.',
  Tooltip: 'Help text shown when hovering the field in a PDF viewer.',
  Options: 'One choice per line.',
  Value: 'Current value of the field.',
  Layer: 'Layer the object belongs to. Layers can be hidden or locked together.',
  Thickness: 'Thickness of the line in points.',
  'Line style': 'Solid, dashed or dotted line.',
  'Border colour': 'Colour of the border line.',
  'Border width': 'Thickness of the border in points.',
  'Border thickness': 'Thickness of the border in points.',
  'Stamp text': 'The words shown on the stamp.',
  'Stamp colour': 'Colour of the stamp.',
  'Stamp preset': 'Ready-made stamps such as APPROVED, DRAFT or CONFIDENTIAL.',
  'Show date': 'Print today’s date under the stamp text.',
  Dynamic: 'The stamp shows the date at export time instead of a fixed date.',
  'Redaction reason': 'Reason recorded with the redaction (shown on the box).',
  'Redaction colour': 'Colour of the box that covers the redacted area.',
  'Overlay text': 'Text printed on top of the redaction box, for example “REDACTED”.',
  'Markup colour': 'Colour of the highlight, underline or strikeout.',
  'Markup style': 'Highlight, underline, strikeout or squiggly.',
  'Markup mode': 'Select text, or drag an area (useful for scanned pages without text).',
  'Fill colour': 'Colour that fills the inside of the shape.',
  'Stroke colour': 'Colour of the outline.',
  'Star points': 'How many points the star has.',
  Points: 'Number of corners of the polygon.',
  Radius: 'How rounded the corners are.',
  'Corner radius': 'How rounded the corners are.',
  'Line ends': 'Arrowheads at the start and/or end of the line.',
  Ends: 'Arrowheads at the start and/or end of the line.',
  Validation: 'Rule the field value must follow: number, email, pattern or maximum length.',
  'Validation pattern': 'Regular expression the value must match.',
  'Validation message': 'Message shown when the value is not valid.',
  Pattern: 'Regular expression the value must match.',
  'Maximum length': 'Longest value that is accepted.',
  'Tab order': 'Order in which the Tab key moves between fields.',
  Type: 'Kind of field or link.',
  'Link type': 'Web address, email address or another page of this document.',
  'Link border width': 'Thickness of the border drawn around the link area.',
  'Link border style': 'Solid, dashed or no border around the link area.',
  'Link border colour': 'Colour of the border drawn around the link area.',
  'Crop top': 'How much to cut from the top edge, in points.',
  'Crop bottom': 'How much to cut from the bottom edge, in points.',
  'Crop left': 'How much to cut from the left edge, in points.',
  'Crop right': 'How much to cut from the right edge, in points.',
  'Field name': 'Internal name of the field. Fields with the same name share one value.',
  'Field value': 'The value currently entered in the field.',
  'Default value': 'Value the field returns to when the form is reset.',
  'Choice value': 'Value stored when this choice is selected.',
  'Radio export value': 'Value exported when this radio button is selected.',
  'Button label': 'Text shown on the button.',
  'Field font size': 'Text size used inside the field.',
  'Note colour': 'Colour of the sticky note icon.',
  Author: 'Name shown as the author of the annotation.',
  Message: 'Text shown to the user.',
  'Replacement text': 'Text that replaces every match.',
  Title: 'Title of the document or bookmark.',
  Source: 'Where the page comes from (file and page number).',
  Compression: 'How strongly images are recompressed. Stronger means smaller files and lower quality.',
  Encryption: 'Whether the document is password protected.',
  'Crop / frame': 'Visible area and output page frame of the page.',
  Pages: 'Which pages the action applies to.',
  Page: 'Current page number.',
  Zoom: 'How large the pages are shown.',
  'Zoom preset': 'Fit the page to the window width, height or whole page.',
  'Zoom percentage (custom zoom)': 'Type a zoom percentage.',
  'Page layout': 'Single, continuous or two-page layout.',
  'Text content': 'The text shown in the object. Changes appear on the page immediately.',
  Text: 'The text and font settings of this object.',
}
