import { PDFDict, PDFDocument, PDFName } from 'pdf-lib'
import { expect, test } from '@playwright/test'
import { FIX, clickPage, dragOnPage, downloadBytes, gotoEditor, openFiles, pagePoint, pdfTexts, runCommand, saveAndGetBytes } from './helpers'

test.describe('viewer interaction @cross', () => {
  test('selecting text with the mouse and highlighting it (text mode), then copy', async ({ page, context }) => {
    await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: 'http://localhost:3000' }).catch(() => {})
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await expect(page.locator('.pdf-text-layer span').first()).toBeAttached({ timeout: 15000 })
    // native selection over the text line (default select tool)
    const line = page.locator('.pdf-text-layer span', { hasText: 'quick brown fox' }).first()
    await line.dblclick()
    const sel = await page.evaluate(() => window.getSelection()?.toString() ?? '')
    expect(sel.length).toBeGreaterThan(2)
    // highlight it through the context menu
    await line.click({ button: 'right' })
    await expect(page.getByTestId('context-menu')).toBeVisible()
    await page.getByRole('menuitem', { name: 'Highlight' }).click()
    await expect(page.locator('[data-obj][data-type=markup]')).toHaveCount(1)
    // and by dragging with the highlight tool active
    await runCommand(page, 'tool.underline')
    const box = (await line.boundingBox())!
    await page.mouse.move(box.x + 4, box.y + box.height / 2)
    await page.mouse.down()
    await page.mouse.move(box.x + box.width * 0.6, box.y + box.height / 2, { steps: 6 })
    await page.mouse.up()
    await expect(page.locator('[data-obj][data-type=markup]')).toHaveCount(2)
  })

  test('context menus: page, object and text selection', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    const [x, y] = await pagePoint(page, 0.8, 0.5)
    await page.mouse.click(x, y, { button: 'right' })
    const menu = page.getByTestId('context-menu')
    await expect(menu).toContainText('Page 1')
    await expect(menu.getByRole('menuitem', { name: /Rotate page clockwise/ })).toBeVisible()
    await page.keyboard.press('Escape')
    await runCommand(page, 'tool.rect')
    await dragOnPage(page, [0.2, 0.6], [0.4, 0.7])
    await page.locator('[data-obj][data-type=shape]').first().click({ button: 'right' })
    await expect(menu).toContainText('shape')
    await expect(menu.getByRole('menuitem', { name: /Duplicate/ })).toBeVisible()
    await menu.getByRole('menuitem', { name: 'Delete' }).click()
    await expect(page.locator('[data-obj][data-type=shape]')).toHaveCount(0)
  })

  test('hand tool pans and ctrl+wheel zooms', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'tool.hand')
    const viewer = page.getByTestId('pdf-viewer')
    const before = await viewer.evaluate((e) => e.scrollTop)
    const b = (await viewer.boundingBox())!
    await page.mouse.move(b.x + b.width / 2, b.y + b.height * 0.7)
    await page.mouse.down()
    await page.mouse.move(b.x + b.width / 2, b.y + b.height * 0.2, { steps: 6 })
    await page.mouse.up()
    expect(await viewer.evaluate((e) => e.scrollTop)).toBeGreaterThan(before + 50)
    const z0 = parseFloat((await viewer.getAttribute('data-zoom'))!)
    await page.mouse.move(b.x + b.width / 2, b.y + b.height / 2)
    await page.keyboard.down('Control')
    await page.mouse.wheel(0, -300)
    await page.keyboard.up('Control')
    await expect.poll(async () => parseFloat((await viewer.getAttribute('data-zoom'))!)).toBeGreaterThan(z0)
  })

  test('search highlights results on the page and navigates between them', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await page.keyboard.press('Control+f')
    await page.getByTestId('search-input').fill('fox')
    await expect(page.getByTestId('search-count')).toContainText('1 of 3', { timeout: 15000 })
    await expect(page.getByTestId('search-highlights').first().locator('div').first()).toBeVisible()
    await page.getByRole('button', { name: 'Next result' }).click()
    await expect(page.getByTestId('search-count')).toContainText('2 of 3')
    await expect(page.getByTestId('status-page')).toContainText('Page 2')
    await page.getByRole('button', { name: 'Previous result' }).click()
    await expect(page.getByTestId('search-count')).toContainText('1 of 3')
    // case sensitive / whole word options change the count
    await page.getByTestId('search-input').fill('FOX')
    await expect(page.getByTestId('search-count')).toContainText('of 3')
    await page.getByLabel('Case sensitive').click()
    await expect(page.getByTestId('search-count')).toContainText('No results')
  })

  test('find & replace overlays the replacement text', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'edit.replace')
    await page.getByTestId('replace-find').fill('lazy dog')
    await page.getByTestId('replace-with').fill('sleepy cat')
    await page.getByTestId('replace-run').click()
    await expect(page.locator('[data-obj][data-type=text]').first()).toBeAttached({ timeout: 20000 })
    const t = await pdfTexts(await saveAndGetBytes(page))
    expect(t[0]).toContain('sleepy cat')
  })

  test('crop tool applies a crop box to the exported page', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'pages.cropTool')
    await dragOnPage(page, [0.1, 0.1], [0.6, 0.5])
    await page.getByRole('button', { name: 'Apply to this page' }).click()
    const doc = await PDFDocument.load(await saveAndGetBytes(page), { updateMetadata: false })
    const { width, height } = doc.getPage(0).getCropBox()
    expect(width).toBeLessThan(400)
    expect(height).toBeLessThan(450)
    expect(doc.getPage(1).getCropBox().width).toBe(612) // only the current page
  })

  test('page setup: add margins and resize keep the export valid', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'pages.setup')
    await page.getByRole('tab', { name: 'Margins' }).click()
    await page.getByTestId('setup-add-margins').click()
    let doc = await PDFDocument.load(await saveAndGetBytes(page), { updateMetadata: false })
    expect(doc.getPage(0).getSize().width).toBeGreaterThan(612)
    await runCommand(page, 'pages.setup')
    await page.getByTestId('setup-resize').click()
    doc = await PDFDocument.load(await saveAndGetBytes(page), { updateMetadata: false })
    expect(Math.round(doc.getPage(0).getSize().width)).toBe(595) // A4
  })

  test('page labels and bookmarks are written to the file', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'pages.labels')
    await page.getByLabel('Numbering style').click()
    await page.getByRole('option', { name: 'i, ii, iii', exact: true }).click()
    await page.getByTestId('labels-apply').click()
    await expect(page.getByTestId('page-total')).toContainText('(i)')
    await runCommand(page, 'pages.bookmark')
    await expect(page.getByTestId('outline-panel').getByRole('treeitem')).toHaveCount(1)
    const doc = await PDFDocument.load(await saveAndGetBytes(page), { updateMetadata: false })
    expect(doc.catalog.has(PDFName.of('PageLabels'))).toBe(true)
    expect(doc.catalog.lookup(PDFName.of('Outlines'), PDFDict).get(PDFName.of('Count'))?.toString()).toBe('1')
  })

  test('layers: hide a layer, lock, and the hidden layer is not exported', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'text.add')
    await dragOnPage(page, [0.15, 0.6], [0.7, 0.66])
    await page.getByLabel('Type text').fill('LAYERED-TEXT')
    await page.getByTestId('status-page').click()
    await page.getByTestId('tab-layers').click()
    await page.getByRole('button', { name: /Hide Annotations/ }).click()
    await expect(page.locator('[data-obj][data-type=text]')).toHaveCount(0)
    expect((await pdfTexts(await saveAndGetBytes(page)))[0]).not.toContain('LAYERED-TEXT')
    await page.getByRole('button', { name: /Show Annotations/ }).click()
    expect((await pdfTexts(await saveAndGetBytes(page)))[0]).toContain('LAYERED-TEXT')
  })

  test('attachments are embedded in the exported PDF', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await page.getByTestId('tab-attachments').click()
    const [chooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByRole('button', { name: /Attach file/ }).click()])
    await chooser.setFiles(FIX('pixel.png'))
    await expect(page.getByTestId('attachments-panel')).toContainText('pixel.png')
    const doc = await PDFDocument.load(await saveAndGetBytes(page), { updateMetadata: false })
    expect(doc.getAttachments().map((a) => a.name)).toEqual(['pixel.png'])
  })

  test('image filters: brightness/grayscale applied, image can be cropped and replaced', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    const [chooser] = await Promise.all([page.waitForEvent('filechooser'), runCommand(page, 'image.insert')])
    await chooser.setFiles(FIX('pixel.png'))
    await clickPage(page, 0.5, 0.65)
    const img = page.locator('[data-obj][data-type=image] img')
    await expect(img).toHaveCount(1)
    await page.getByRole('slider', { name: 'Grayscale' }).press('End')
    await expect(img).toHaveCSS('filter', /grayscale/)
    await page.getByLabel('Crop left').fill('25')
    await page.getByRole('slider', { name: /JPEG quality/ }).press('Home')
    const bytes = await saveAndGetBytes(page)
    expect(new TextDecoder('latin1').decode(bytes)).toContain('/DCTDecode') // quality < 100% → JPEG embedding
  })

  test('downloads are named safely', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    const [dl] = await Promise.all([page.waitForEvent('download'), page.keyboard.press('Control+s')])
    expect(dl.suggestedFilename()).toBe('sample.pdf')
    expect((await downloadBytes(dl)).length).toBeGreaterThan(500)
  })
})
