import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'
import { FIX, clickPage, dragOnPage, gotoEditor, openFiles, pdfTexts, runCommand, saveAndGetBytes, waitSaved } from './helpers'

test.describe('persistence & offline @cross', () => {
  test('autosave + reload restores the project with its edits', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'text.add')
    await dragOnPage(page, [0.15, 0.6], [0.7, 0.66])
    await page.getByLabel('Type text').fill('Persisted across reload')
    await page.getByTestId('status-page').click()
    await expect(page.locator('[data-obj][data-type=text]')).toHaveCount(1)
    await waitSaved(page)
    await page.reload()
    await expect(page.getByTestId('recent-projects')).toBeVisible({ timeout: 15000 })
    await expect(page.getByTestId('recent-projects')).toContainText('sample.pdf')
    await page.getByTestId('restore-project').first().click()
    await page.waitForSelector('[data-testid=pdf-page] canvas')
    await expect(page.locator('[data-obj][data-type=text]')).toHaveCount(1)
    const texts = await pdfTexts(await saveAndGetBytes(page))
    expect(texts[0]).toContain('Persisted across reload')
    expect(texts[0]).toContain('Sample 1')
  })

  test('projects dialog: rename, duplicate, export/import file, versions, delete', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'tool.rect')
    await dragOnPage(page, [0.2, 0.6], [0.4, 0.7])
    await waitSaved(page)
    await runCommand(page, 'file.projects')
    const list = page.getByTestId('project-list')
    await expect(list.locator('li')).toHaveCount(1)
    await page.getByRole('button', { name: /Duplicate sample\.pdf/ }).click()
    await expect(list.locator('li')).toHaveCount(2)
    await page.getByRole('tab', { name: 'Version history' }).click()
    await page.getByRole('button', { name: /Save a version now/ }).click()
    await expect(page.getByText('Manual version')).toBeVisible({ timeout: 20000 })
    await page.getByRole('tab', { name: 'Projects' }).click()
    await page.getByRole('button', { name: /Delete sample copy\.pdf/ }).click()
    await page.getByTestId('confirm-ok').click()
    await expect(list.locator('li')).toHaveCount(1)
  })

  test('works offline after the first visit (service worker + cached engine)', async ({ page, context }) => {
    test.setTimeout(150000)
    await page.goto('/editor')
    await expect(page.getByTestId('onboarding')).toBeVisible()
    // wait until the service worker controls the page and has precached the shell
    await page.evaluate(async () => { const reg = await navigator.serviceWorker.ready; return reg.active?.state })
    await expect.poll(async () => page.evaluate(async () => { const keys = await caches.keys(); let n = 0; for (const k of keys) n += (await (await caches.open(k)).keys()).length; return n }), { timeout: 60000 }).toBeGreaterThan(20)
    await page.reload() // now controlled by the SW
    await expect(page.getByTestId('onboarding')).toBeVisible()
    await context.setOffline(true)
    await page.reload()
    await expect(page.getByTestId('onboarding')).toBeVisible({ timeout: 20000 })
    await openFiles(page, [FIX('sample.pdf')])
    await expect(page.getByTestId('status-page')).toContainText('Page 1 / 3')
    await runCommand(page, 'text.add')
    await dragOnPage(page, [0.15, 0.6], [0.7, 0.66])
    await page.getByLabel('Type text').fill('written offline')
    await page.getByTestId('status-page').click()
    const texts = await pdfTexts(await saveAndGetBytes(page)) // export runs in the cached worker
    expect(texts[0]).toContain('written offline')
    // an uncached route falls back to the offline page
    await page.goto('/offline')
    await expect(page.getByRole('heading', { name: /offline/i })).toBeVisible()
    await context.setOffline(false)
  })

  test('no network request ever leaves the origin during a full editing workflow', async ({ page }) => {
    const external: string[] = []
    page.on('request', (r) => { const u = new URL(r.url()); if (u.protocol.startsWith('http') && u.hostname !== 'localhost') external.push(r.url()) })
    await gotoEditor(page)
    await openFiles(page, [FIX('form.pdf')])
    await runCommand(page, 'tool.rect')
    await dragOnPage(page, [0.2, 0.6], [0.4, 0.7])
    await runCommand(page, 'opt.compress')
    await page.getByTestId('compress-run').click()
    await expect(page.getByTestId('compress-result')).toBeVisible({ timeout: 40000 })
    await page.keyboard.press('Escape')
    await saveAndGetBytes(page)
    expect(external).toEqual([])
  })
})

test.describe('shortcuts & accessibility @cross', () => {
  test('required keyboard shortcuts work', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    // zoom
    const zoom = async () => parseFloat((await page.getByTestId('pdf-viewer').getAttribute('data-zoom')) ?? '1')
    const z0 = await zoom()
    await page.keyboard.press('Control+=')
    await expect.poll(zoom).toBeGreaterThan(z0 + 0.05)
    await page.keyboard.press('Control+-')
    await page.keyboard.press('Control+-')
    await expect.poll(zoom).toBeLessThan(z0)
    // search
    await page.keyboard.press('Control+f')
    await expect(page.getByTestId('search-input')).toBeFocused()
    await page.getByTestId('search-input').fill('lazy dog')
    await expect(page.getByTestId('search-count')).toContainText('1 of 3', { timeout: 15000 })
    await page.keyboard.press('Escape')
    // escape cancels a tool
    await runCommand(page, 'tool.rect')
    await expect(page.getByTestId('creation-layer').first()).toBeAttached()
    await page.locator('body').click({ position: { x: 5, y: 5 } })
    await page.keyboard.press('Escape')
    await expect(page.getByTestId('creation-layer')).toHaveCount(0)
    // delete selected + undo/redo
    await runCommand(page, 'tool.rect')
    await dragOnPage(page, [0.2, 0.6], [0.4, 0.7])
    await page.keyboard.press('Delete')
    await expect(page.locator('[data-obj][data-type=shape]')).toHaveCount(0)
    await page.keyboard.press('Control+z')
    await expect(page.locator('[data-obj][data-type=shape]')).toHaveCount(1)
    await page.keyboard.press('Control+Shift+z')
    await expect(page.locator('[data-obj][data-type=shape]')).toHaveCount(0)
    // space pans
    await page.keyboard.down('Space')
    await expect(page.getByTestId('pdf-viewer')).toHaveCSS('cursor', 'grab')
    await page.keyboard.up('Space')
  })

  test('Ctrl+O opens the file picker; Ctrl+P opens print; shortcut customisation works', async ({ page }) => {
    await gotoEditor(page)
    const [chooser] = await Promise.all([page.waitForEvent('filechooser'), page.keyboard.press('Control+o')])
    await chooser.setFiles(FIX('sample.pdf'))
    await page.waitForSelector('[data-testid=pdf-page] canvas')
    await page.keyboard.press('Control+p')
    await expect(page.getByTestId('dialog-print')).toBeVisible()
    await page.keyboard.press('Escape')
    // customise: bind Alt+T to "Add text"
    await runCommand(page, 'help.shortcuts')
    await page.getByRole('button', { name: 'Change shortcut for Add text', exact: true }).click()
    await page.keyboard.press('Alt+t')
    await expect(page.getByRole('button', { name: 'Change shortcut for Add text', exact: true })).toContainText('Alt+T')
    await page.getByRole('button', { name: 'Done' }).click()
    await page.keyboard.press('Alt+t')
    await expect(page.getByTestId('options-text')).toBeVisible()
  })

  test('dialogs are accessible: labelled, focus-trapped, Escape closes and focus returns', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await page.getByRole('menuitem', { name: 'Tools' }).or(page.getByText('Tools', { exact: true }).first()).click()
    await page.locator('[data-command="ocr.run"]').click()
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible()
    await expect(dialog).toHaveAttribute('aria-labelledby', /.+/)
    const results = await new AxeBuilder({ page }).include('[role=dialog]').withTags(['wcag2a', 'wcag2aa']).disableRules(['color-contrast']).analyze()
    expect(results.violations.filter((v) => ['serious', 'critical'].includes(v.impact ?? ''))).toEqual([])
    for (let i = 0; i < 12; i++) await page.keyboard.press('Tab')
    expect(await page.evaluate(() => !!document.activeElement?.closest('[role=dialog]'))).toBe(true)
    await page.keyboard.press('Escape')
    await expect(dialog).toBeHidden()
  })

  test('menus are keyboard operable and toolbar buttons have accessible names', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await page.getByRole('menuitem', { name: 'File' }).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('menu')).toBeVisible()
    await page.keyboard.press('Escape')
    const unnamed = await page.evaluate(() => Array.from(document.querySelectorAll('button')).filter((b) => !(b.textContent?.trim() || b.getAttribute('aria-label') || b.getAttribute('title') || b.getAttribute('aria-labelledby')) && b.offsetParent !== null).map((b) => b.outerHTML.slice(0, 100)))
    expect(unnamed).toEqual([])
  })

  test('dark mode, high contrast and reduced motion settings apply', async ({ page }) => {
    await gotoEditor(page)
    await runCommand(page, 'view.theme')
    await expect(page.locator('html')).toHaveClass(/dark/)
    await runCommand(page, 'view.highContrast')
    await expect(page.locator('html')).toHaveClass(/hc/)
    await runCommand(page, 'view.reduceMotion')
    await expect(page.locator('html')).toHaveClass(/reduce-motion/)
  })

  test('command palette finds crop, merge, ocr, signature, watermark, compress', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    for (const [q, id] of [['crop', 'pages.crop'], ['merge', 'file.merge'], ['ocr', 'ocr.run'], ['signature', 'sign.create'], ['watermark', 'wm.add'], ['compress', 'opt.compress']] as const) {
      await page.keyboard.press('Control+k')
      await page.getByTestId('palette-input').fill(q)
      await expect(page.locator(`[cmdk-item][data-command="${id}"]`).first()).toBeVisible()
      await page.keyboard.press('Escape')
    }
  })

  test('view modes: single, two-page, presentation, fit modes and rotation', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'view.two')
    await expect.poll(() => page.locator('[data-testid=pdf-page]').count()).toBeGreaterThanOrEqual(2)
    await runCommand(page, 'view.single')
    await expect.poll(() => page.locator('[data-testid=pdf-page]').count()).toBe(1)
    await page.keyboard.press('PageDown')
    await expect(page.getByTestId('status-page')).toContainText('Page 2')
    await runCommand(page, 'view.horizontal')
    await runCommand(page, 'view.presentation')
    await expect(page.getByTestId('presentation')).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByTestId('editor-shell')).toBeVisible()
  })
})

test.describe('mobile @mobile', () => {
  test('landing page fits the viewport', async ({ page }) => {
    await page.goto('/')
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  })

  test('editor: hamburger menu, pages sheet, properties drawer, no horizontal overflow', async ({ page }) => {
    await gotoEditor(page)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
    const [chooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByTestId('onboarding-open').click()])
    await chooser.setFiles(FIX('sample.pdf'))
    await page.waitForSelector('[data-testid=pdf-page] canvas')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
    await page.getByRole('button', { name: 'Menu' }).click()
    await expect(page.getByTestId('mobile-menu').getByRole('button', { name: 'File', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Open pages and panels' }).click()
    await expect(page.getByTestId('left-sidebar')).toBeVisible()
    await page.getByRole('button', { name: 'Close', exact: true }).click()
    await expect(page.getByTestId('left-sidebar')).toBeHidden()
    await clickPage(page, 0.5, 0.5)
    await page.getByRole('button', { name: 'Open properties' }).click()
    await expect(page.getByTestId('properties-panel')).toBeVisible()
  })

  test('touch: add a shape with a finger-sized drag', async ({ page }) => {
    await gotoEditor(page)
    const [chooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByTestId('onboarding-open').click()])
    await chooser.setFiles(FIX('sample.pdf'))
    await page.waitForSelector('[data-testid=pdf-page] canvas')
    await runCommand(page, 'tool.rect')
    await dragOnPage(page, [0.2, 0.5], [0.6, 0.6])
    await expect(page.locator('[data-obj][data-type=shape]')).toHaveCount(1)
  })
})
