import { PDFDocument, PDFName } from 'pdf-lib'
import JSZip from 'jszip'
import { expect, test, type Page } from '@playwright/test'
import { FIX, clickPage, downloadBytes, dragOnPage, gotoEditor, openFiles, pageCount, pdfTexts, runCommand, saveAndGetBytes } from './helpers'

const objs = (page: Page, type: string) => page.locator(`[data-obj][data-type=${type}]`)

test.describe('annotations, text, images @cross', () => {
  test('sticky note, area highlight and freehand drawing', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'tool.note')
    await clickPage(page, 0.7, 0.3)
    await expect(objs(page, 'note')).toHaveCount(1)
    await page.getByLabel('Note text').fill('Check this figure')
    await runCommand(page, 'tool.highlight')
    await page.getByRole('radio', { name: 'Area' }).or(page.getByText('Area', { exact: true })).first().click()
    await dragOnPage(page, [0.15, 0.32], [0.6, 0.36])
    await expect(objs(page, 'markup')).toHaveCount(1)
    await runCommand(page, 'tool.pen')
    await dragOnPage(page, [0.2, 0.7], [0.5, 0.8])
    await expect(objs(page, 'ink')).toHaveCount(1)
    const bytes = await saveAndGetBytes(page)
    const doc = await PDFDocument.load(bytes, { updateMetadata: false })
    const annots = doc.getPage(0).node.Annots()!
    expect(annots.size()).toBe(1) // the sticky note is a native annotation
    const text = (annots.lookup(0) as import('pdf-lib').PDFDict).get(PDFName.of('Subtype'))!.toString()
    expect(text).toBe('/Text')
  })

  test('shapes, move by keyboard, resize by handle, z-order and delete', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'tool.ellipse')
    await dragOnPage(page, [0.2, 0.55], [0.5, 0.7])
    const shape = objs(page, 'shape').first()
    await expect(shape).toBeVisible()
    const before = await shape.boundingBox()
    await page.keyboard.press('Shift+ArrowRight')
    await expect.poll(async () => (await shape.boundingBox())!.x).toBeGreaterThan(before!.x + 5)
    const h = page.locator('[data-handle="se"]')
    const hb = await h.boundingBox()
    await page.mouse.move(hb!.x + hb!.width / 2, hb!.y + hb!.height / 2)
    await page.mouse.down()
    await page.mouse.move(hb!.x + 80, hb!.y + 50, { steps: 5 })
    await page.mouse.up()
    await expect.poll(async () => (await shape.boundingBox())!.width).toBeGreaterThan(before!.width + 40)
    await page.keyboard.press('Delete')
    await expect(objs(page, 'shape')).toHaveCount(0)
    await page.keyboard.press('Control+z')
    await expect(objs(page, 'shape')).toHaveCount(1)
  })

  test('text formatting: bold, size and colour end up in the exported PDF', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'text.add')
    await dragOnPage(page, [0.15, 0.6], [0.8, 0.66])
    await page.getByLabel('Type text').fill('Styled heading text')
    await page.getByTestId('status-page').click()
    await page.getByRole('button', { name: 'Bold' }).last().click()
    await page.getByLabel('Font size').last().fill('30')
    const raw = new TextDecoder('latin1').decode(await saveAndGetBytes(page))
    expect(raw).toContain('Helvetica-Bold')
  })

  test('edit existing text: click a line, retype, and the page shows the replacement', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'text.edit')
    // the 'quick brown fox' line has its baseline at y=650pt of 792 → its glyph box is ~16–18% down the page
    await clickPage(page, 0.3, 0.172)
    // the line is selected right away: its text is in the Properties panel and can be changed there
    const ta = page.getByLabel('Text content')
    await expect(ta).toBeVisible({ timeout: 10000 })
    await expect(ta).toHaveValue(/quick brown fox/)
    await page.getByTestId('status-page').click()
    await ta.fill('The slow purple cat sleeps.')
    await expect(objs(page, 'text')).toHaveCount(1)
    const t = (await pdfTexts(await saveAndGetBytes(page)))[0]
    expect(t).toContain('The slow purple cat sleeps.')
  })

  test('insert an image, adjust it and export', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    const [chooser] = await Promise.all([page.waitForEvent('filechooser'), runCommand(page, 'image.insert')])
    await chooser.setFiles(FIX('pixel.png'))
    await clickPage(page, 0.5, 0.65)
    await expect(objs(page, 'image')).toHaveCount(1)
    await page.getByRole('button', { name: 'Flip horizontally' }).click()
    await page.getByLabel('Rotation').fill('15')
    const bytes = await saveAndGetBytes(page)
    expect(new TextDecoder('latin1').decode(bytes)).toContain('/Subtype /Image')
  })

  test('paste an image from the clipboard', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await page.evaluate(async () => {
      const c = document.createElement('canvas'); c.width = 40; c.height = 30
      const ctx = c.getContext('2d')!; ctx.fillStyle = '#0a0'; ctx.fillRect(0, 0, 40, 30)
      const blob: Blob = await new Promise((r) => c.toBlob((b) => r(b!), 'image/png'))
      const dt = new DataTransfer(); dt.items.add(new File([blob], 'clip.png', { type: 'image/png' }))
      document.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true }))
    })
    await expect(objs(page, 'image')).toHaveCount(1)
  })

  test('copy / paste / duplicate objects and select all', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'tool.rect')
    await dragOnPage(page, [0.2, 0.6], [0.4, 0.7])
    await page.keyboard.press('Control+c')
    await page.keyboard.press('Control+v')
    await expect(objs(page, 'shape')).toHaveCount(2)
    await page.keyboard.press('Control+d')
    await expect(objs(page, 'shape')).toHaveCount(3)
    await page.keyboard.press('Control+a')
    await expect(page.getByTestId('statusbar')).toContainText('3 objects selected')
  })

  test('links: URL link exports as a native link annotation; unsafe schemes are rejected', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'annotate.link')
    await dragOnPage(page, [0.15, 0.17], [0.6, 0.2])
    await expect(page.getByTestId('dialog-link')).toBeVisible()
    await page.getByTestId('link-url').fill('javascript:alert(1)')
    await page.getByTestId('link-save').click()
    await expect(page.locator('[data-sonner-toast]').filter({ hasText: /valid/ }).first()).toBeVisible()
    await page.getByTestId('link-url').fill('https://example.com/docs')
    await page.getByTestId('link-save').click()
    const doc = await PDFDocument.load(await saveAndGetBytes(page), { updateMetadata: false })
    const annots = doc.getPage(0).node.Annots()!
    const a = annots.lookup(0) as import('pdf-lib').PDFDict
    expect(a.get(PDFName.of('Subtype'))!.toString()).toBe('/Link')
    const action = a.lookup(PDFName.of('A')) as import('pdf-lib').PDFDict
    expect(action.get(PDFName.of('URI'))!.toString()).toContain('example.com/docs')
  })

  test('stamps, watermark and footer page numbers appear in the export', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'annotate.stampDialog')
    await page.getByTestId('stamp-approved').click()
    await clickPage(page, 0.6, 0.6)
    await runCommand(page, 'wm.add')
    await page.getByTestId('wm-text').fill('DRAFT COPY')
    await page.getByTestId('wm-apply').click()
    await page.keyboard.press('Escape')
    await runCommand(page, 'hf.footer')
    await page.getByTestId('hf-footer-center').fill('Page {page} of {total}')
    await page.getByTestId('hf-apply').click()
    await page.keyboard.press('Escape')
    const texts = await pdfTexts(await saveAndGetBytes(page))
    expect(texts[0]).toContain('APPROVED')
    expect(texts[0]).toContain('DRAFT COPY')
    expect(texts[0]).toContain('Page 1 of 3')
    expect(texts[2]).toContain('Page 3 of 3')
  })
})

test.describe('forms & signatures @cross', () => {
  test('existing form fields are imported, fillable, validated and saved', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('form.pdf')])
    await expect(objs(page, 'field')).toHaveCount(3, { timeout: 20000 })
    const name = page.getByLabel('full_name')
    await expect(name).toHaveValue('Alice Example')
    await name.fill('Bob Builder')
    await page.getByLabel('agree').check()
    const form = (await PDFDocument.load(await saveAndGetBytes(page), { updateMetadata: false })).getForm()
    expect(form.getTextField('full_name').getText()).toBe('Bob Builder')
    expect(form.getCheckBox('agree').isChecked()).toBe(true)
    expect(form.getDropdown('country').getSelected()).toEqual(['India'])
  })

  test('build a form: text field with required + validation, checkbox, export data, flatten', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'form.field-text')
    await dragOnPage(page, [0.15, 0.7], [0.55, 0.74])
    await expect(objs(page, 'field')).toHaveCount(1)
    await page.getByLabel('Field name').fill('email')
    await page.getByLabel('Tooltip').fill('Your email')
    await page.getByRole('checkbox', { name: /Required/ }).or(page.getByLabel('Required')).first().click().catch(() => {})
    await runCommand(page, 'form.field-checkbox')
    await dragOnPage(page, [0.15, 0.78], [0.2, 0.8])
    await expect(objs(page, 'field')).toHaveCount(2)
    // fill mode + validation
    await runCommand(page, 'form.fill')
    await page.getByLabel('Your email').fill('nope')
    const bytes = await saveAndGetBytes(page)
    const form = (await PDFDocument.load(bytes, { updateMetadata: false })).getForm()
    const names = form.getFields().map((f) => f.getName())
    expect(names).toEqual(expect.arrayContaining(['email']))
    expect(form.getTextField('email').getText()).toBe('nope')
    // export form data
    await runCommand(page, 'form.data')
    const [dl] = await Promise.all([page.waitForEvent('download'), page.getByTestId('form-export-json').click()])
    const json = JSON.parse(new TextDecoder().decode(await downloadBytes(dl)))
    expect(json.fields.email).toBe('nope')
  })

  test('type a signature, place it, and it is embedded; saved signatures persist across reloads', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'sign.create')
    await expect(page.getByTestId('dialog-sign')).toContainText('not a certificate-based digital signature')
    await page.getByTestId('sign-tab-type').click()
    await page.getByTestId('sign-typed').fill('Alex Doe')
    await page.getByTestId('sign-use').click()
    await expect(page.getByTestId('dialog-sign')).toBeHidden()
    await clickPage(page, 0.5, 0.7)
    await expect(page.locator('[data-obj][data-type=image] img[alt=Signature]')).toHaveCount(1)
    expect(new TextDecoder('latin1').decode(await saveAndGetBytes(page))).toContain('/Subtype /Image')
    await page.reload()
    await expect(page.getByTestId('onboarding')).toBeVisible()
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'sign.create')
    await page.getByTestId('sign-tab-saved').click()
    await expect(page.getByTestId('use-saved-signature')).toHaveCount(1)
  })

  test('draw a signature on the pad', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'sign.create')
    const pad = page.getByTestId('signature-pad')
    const b = (await pad.boundingBox())!
    await page.mouse.move(b.x + 40, b.y + b.height / 2)
    await page.mouse.down()
    for (let i = 0; i < 12; i++) await page.mouse.move(b.x + 40 + i * 25, b.y + b.height / 2 + Math.sin(i) * 30)
    await page.mouse.up()
    await page.getByTestId('sign-use').click()
    await expect(page.getByTestId('dialog-sign')).toBeHidden()
    await clickPage(page, 0.4, 0.75)
    await expect(objs(page, 'image')).toHaveCount(1)
  })
})

test.describe('security, optimisation, conversion @cross', () => {
  test('redaction permanently removes the text from the file', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'sec.redactText')
    await page.getByTestId('redact-query').fill('123-456-789')
    await expect(page.getByTestId('redact-count')).toContainText('3 matches', { timeout: 15000 })
    await page.getByTestId('redact-mark').click()
    await expect(objs(page, 'redact').first()).toBeVisible()
    await runCommand(page, 'sec.applyRedactions')
    await page.getByTestId('confirm-ok').click()
    await expect(page.locator('[data-sonner-toast]').filter({ hasText: /Redactions applied/ })).toBeVisible({ timeout: 40000 })
    const bytes = await saveAndGetBytes(page)
    const raw = new TextDecoder('latin1').decode(bytes)
    const texts = await pdfTexts(bytes)
    for (const t of texts) expect(t).not.toContain('123-456-789')
    expect(raw).not.toContain('123-456-789')
    // non-redacted text is still selectable/searchable
    expect(texts[0]).toContain('Sample 1')
    expect(texts[0]).toContain('quick brown fox')
  })

  test('encrypting produces a password-protected PDF', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'sec.security')
    await expect(page.getByTestId('dialog-security')).toContainText('Permission flags')
    await page.getByTestId('sec-user').fill('s3cret')
    const [dl] = await Promise.all([page.waitForEvent('download'), page.getByTestId('sec-encrypt').click()])
    const bytes = await downloadBytes(dl)
    await expect(PDFDocument.load(bytes)).rejects.toThrow(/encrypt/i)
    expect(await pageCount(bytes, 's3cret')).toBe(3)
  })

  test('metadata editing and removal', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'file.metadata')
    await page.getByTestId('meta-title').fill('Quarterly Report')
    await page.getByTestId('meta-author').fill('Finance')
    await page.getByTestId('meta-save').click()
    let doc = await PDFDocument.load(await saveAndGetBytes(page), { updateMetadata: false })
    expect(doc.getTitle()).toBe('Quarterly Report')
    expect(doc.getAuthor()).toBe('Finance')
    await runCommand(page, 'file.metadata')
    await page.getByTestId('meta-strip').click()
    await page.getByTestId('meta-save').click()
    doc = await PDFDocument.load(await saveAndGetBytes(page), { updateMetadata: false })
    expect(doc.getTitle()).toBeUndefined()
    expect(doc.getAuthor()).toBeUndefined()
  })

  test('compress shows real before/after sizes and downloads a valid PDF', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'opt.compress')
    await page.getByTestId('compress-run').click()
    await expect(page.getByTestId('compress-result')).toBeVisible({ timeout: 40000 })
    await expect(page.getByTestId('compress-after')).toContainText(/KB|B/)
    const [dl] = await Promise.all([page.waitForEvent('download'), page.getByTestId('compress-download').click()])
    expect(await pageCount(await downloadBytes(dl))).toBe(3)
  })

  test('PDF → PNG export downloads one image per page', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'convert.toPng')
    const [dl] = await Promise.all([page.waitForEvent('download'), page.getByTestId('convert-images-run').click()])
    const zip = await JSZip.loadAsync(await downloadBytes(dl))
    const names = Object.keys(zip.files)
    expect(names).toHaveLength(3)
    const head = await zip.files[names[0]].async('uint8array')
    expect(Array.from(head.slice(0, 4))).toEqual([0x89, 0x50, 0x4e, 0x47])
  })

  test('PDF → text and HTML', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'convert.toText')
    const [dl] = await Promise.all([page.waitForEvent('download'), page.getByTestId('convert-text-run').click()])
    expect(new TextDecoder().decode(await downloadBytes(dl))).toContain('The quick brown fox')
    await runCommand(page, 'convert.toHtml')
    const [dl2] = await Promise.all([page.waitForEvent('download'), page.getByTestId('convert-html-run').click()])
    const html = new TextDecoder().decode(await downloadBytes(dl2))
    expect(html).toContain('<section class="page"')
    expect(html).not.toContain('<script')
  })

  test('HTML → PDF sanitises scripts and text → PDF works', async ({ page }) => {
    await gotoEditor(page)
    await runCommand(page, 'convert.dialog')
    await page.getByTestId('tab-topdf').click()
    await page.getByTestId('convert-source').fill('<h1>Hello Title</h1><p>Body <b>bold</b> text</p><script>alert(1)</script><img src="https://evil.example/x.png"><ul><li>One</li><li>Two</li></ul>')
    await page.getByTestId('convert-source-run').click()
    await expect(page.getByTestId('status-page')).toContainText('Page 1', { timeout: 30000 })
    const texts = await pdfTexts(await saveAndGetBytes(page))
    expect(texts[0]).toContain('Hello Title')
    expect(texts[0]).toContain('One')
    expect(texts[0]).not.toContain('alert')
  })

  test('print preview renders the edited document', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'file.print')
    await page.getByTestId('print-preview').click()
    await expect(page.getByTestId('print-preview-grid').locator('img')).toHaveCount(3, { timeout: 40000 })
  })

  test('annotations JSON export (Instant-JSON style)', async ({ page }) => {
    await gotoEditor(page)
    await openFiles(page, [FIX('sample.pdf')])
    await runCommand(page, 'tool.rect')
    await dragOnPage(page, [0.2, 0.6], [0.4, 0.7])
    await runCommand(page, 'convert.exportAnnotations')
    const [dl] = await Promise.all([page.waitForEvent('download'), page.getByTestId('convert-annotations-run').click()])
    const json = JSON.parse(new TextDecoder().decode(await downloadBytes(dl)))
    expect(json.format).toContain('instant-json')
    expect(json.annotations).toHaveLength(1)
    expect(json.annotations[0].type).toBe('pspdfkit/shape')
  })
})

test.describe('OCR @cross', () => {
  test('recognises text in an image locally, offers search, copy and searchable-PDF export', async ({ page }) => {
    test.setTimeout(240000)
    const external: string[] = []
    page.on('request', (r) => { const u = new URL(r.url()); if (!['localhost', '127.0.0.1'].includes(u.hostname) && !['data:', 'blob:'].includes(u.protocol)) external.push(r.url()) })
    await gotoEditor(page)
    await page.getByTestId('onboarding-images').click()
    const [chooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByTestId('images-add').click()])
    await chooser.setFiles(FIX('ocr-text.png'))
    await page.getByTestId('images-run').click()
    await page.waitForSelector('[data-testid=pdf-page] canvas', { timeout: 30000 })
    await runCommand(page, 'ocr.run')
    await expect(page.getByTestId('lang-eng')).toBeVisible()
    await page.getByTestId('ocr-run').click()
    await expect(page.getByTestId('ocr-results')).toBeVisible({ timeout: 200000 })
    const text = await page.getByTestId('ocr-text').inputValue()
    expect(text.toLowerCase()).toContain('hello')
    expect(text.toLowerCase()).toContain('invoice')
    // searchable PDF export contains the recognised words as text
    const [dl] = await Promise.all([page.waitForEvent('download'), page.getByTestId('ocr-searchable').click()])
    const t = (await pdfTexts(await downloadBytes(dl))).join(' ').toLowerCase()
    expect(t).toContain('hello')
    // search finds OCR text in the viewer
    await page.keyboard.press('Escape')
    await page.keyboard.press('Control+f')
    await page.getByTestId('search-input').fill('invoice')
    await expect(page.getByTestId('search-count')).toContainText('1 of', { timeout: 15000 })
    expect(external).toEqual([]) // no request left this origin (language data & engine are self-hosted)
  })

  test('OCR can be cancelled', async ({ page }) => {
    test.setTimeout(120000)
    await gotoEditor(page)
    await openFiles(page, [FIX('large-500.pdf')])
    await runCommand(page, 'ocr.run')
    await page.getByTestId('scope-select').click()
    await page.getByRole('option', { name: 'All pages' }).click()
    await page.getByTestId('ocr-run').click()
    await expect(page.getByTestId('ocr-cancel')).toBeVisible({ timeout: 30000 })
    await page.getByTestId('ocr-cancel').click()
    await expect(page.getByTestId('ocr-run')).toBeVisible({ timeout: 30000 })
  })
})
